apiVersion: v1
kind: Service
metadata:
  name: performance-estimator
spec:
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      nodePort: 31000
  selector:
    app: performance-estimator
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: performance-estimator
spec:
  selector:
    matchLabels:
      app: performance-estimator
  template:
    metadata:
      labels:
        app: performance-estimator
    spec:
      containers:
        - name: performance-estimator
          image: marjoluc/performance_estimator:latest
          ports:
            - containerPort: 5000
      restartPolicy: Always
