name: Build Docker Images

env:
  REGISTRY: ghcr.io
  HYSDS_CORE_IMAGE_NAME: ${{ github.repository }}/hysds-core
  MOZART_NAME: ${{ github.repository }}/hysds-mozart
  CELERY_NAME: ${{ github.repository }}/celery-tasks

on: workflow_dispatch

jobs:

  build-core:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.HYSDS_CORE_IMAGE_NAME }}
    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: hysds
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.HYSDS_CORE_IMAGE_NAME }}:unity-v0.0.1
        labels: ${{ steps.meta.outputs.labels }}